name: Criar e Preencher arquivo Readme.md

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  arquivo-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar e preencher README.md
        run: |
          echo "# Gerando Readme.md automaticamente" > README.md
          echo "" >> README.md
          echo "# Trabalho de GitHub Actions" >> README.md
          echo "## André Luiz de Oliveira Zampieri RA: 14623" >> README.md
          echo "## Hendreu Satoshi Zampieri Itami RA: 240061" >> README.md
          
      - name: Commitar e enviar o Readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizando README.md automaticamente" || echo "Nenhuma mudança para commitar"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
