name: Criar e Preencher arquivo Readme.md

on:
  push:
    branches:
      - main

jobs:
  arquivo-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Readme Checkout
        uses: actions/checkout@v4

      - name: Criar e preencher Readme
        run: echo "# Gerando Readme.md automaticamente" > readme.md

      - name: Commitar o Readme
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Atualizando README.md automaticamente" || echo "Nenhuma mudan√ßa para commitar"
            git push
