name: Mostrar data e hora PUSH

on:
  push:
    branches:
      -  main

jobs:
  hour-date:
    runs-on: ubuntu-latest

    steps:
      - name: Date checkout
        uses: actions/checkout@v4

      - name: Get Data e Hora
        run: |
              TZ="America/Sao_Paulo" date +"%Y-%m-%d %H:%M:%S %Z"
